### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by ghoneycutt** [saz/puppet-limits#24]
Hi @saz 

Could you please tag a new release?

Thank you!

**Comment by jeffmccune** [comment]
+1 especially if we could get #26 merged before the release.

**Comment by pgassmann** [comment]
now that #28 is merged, can you bump the version, build and publish a new release?

**Comment by saz** [comment]
Fresh on the forge: v2.5.0

**Comment by ghoneycutt** [comment]
Thanks!
