### ISSUE TITLE
Add support for puppet6

### ISSUE THREAD

**Issue by azbarcea** [saz/puppet-limits#36]
It seems that the module works out of the box with `puppet 6`, however, some metadata and PDK conversion and test are required. Curios if this module is still supported. I see the latest testing is documented to have been done with `puppet 4.9`.

Related to #34

**Comment by azbarcea** [comment]
Cancelled, as although is not specified in `metadata.json`, the travis job also tests for puppet 6: 
https://travis-ci.org/github/saz/puppet-limits

**Comment by saz** [comment]
Looking at https://github.com/saz/puppet-limits/blob/master/metadata.json, puppet 6 is included since version 3.0.4: `"version_requirement": ">= 4.0.0 < 7.0.0"`
Am I missing something?

**Comment by azbarcea** [comment]
Your documentation shows only `4.9+` version supported. I would have expected: `4.9+ - 6+ (<7)`, to mark, that is not only `4+`, but also all other versions on top. As now `7.0` version is available, would have expected to have those specified in the [README.md](https://github.com/saz/puppet-limits/blob/master/README.md)
