### ISSUE TITLE
Can we support prefix configuration for limits ?

### ISSUE THREAD

**Issue by sreerajkksd** [saz/puppet-limits#39]
prefix is useful so that two puppet classes set the same configurations with different defaults and they won't conflict with each other. And the one with the higher prefix will be applied. 

This is already used in sysctl puppet module (ref: https://forge.puppet.com/modules/thias/sysctl).

**Comment by sreerajkksd** [comment]
@saz If I create a PR to implement this feature, would you help in reviewing/approving and releasing ?

**Comment by sreerajkksd** [comment]
@saz any comments on the above ? Really appreciate if you can reply what you think about this.

**Comment by saz** [comment]
@sreerajkksd Sure, send in a PR

**Comment by bschonec** [comment]
Aren't you masking a coding problem by doing this?  If you have two puppet classes trying to set the same configuration then you have an issue with your code.  

I'd make the same argument with sysctl.d as well.  If you are overriding a previous configuration then it'd be best to figure out what's wanting to make those duplicate configs and eliminate the unnecessary configurations.

**Comment by saz** [comment]
As there isn't any progress here, and @bschonec has a valid point, I'm closing this issue. Feel free to send in a PR and I'll reconsider my opinion
