### ISSUE TITLE
How do you set more than one limit type in a single file?

### ISSUE THREAD

**Issue by bschonec** [saz/puppet-limits#42]
My limits.d directory is getting polluted with scores of files.  Is there a way to consolidate all of the limits that I want *per user* into a single file?  I want something that looks like:

apache_user hard fsize unlimited
apache_user soft core unlimited
apache_user hard core unlimited
apache_user soft cpu unlimited
apache_user hard cpu unlimited
apache_user soft data unlimited
apache_user hard data unlimited
apache_user soft stack unlimited
apache_user hard stack unlimited
apache_user soft rss 2097151
apache_user hard rss 2097151
apache_user soft nofile 2000
apache_user hard nofile 2000
apache_user soft nproc 48000
apache_user hard nproc 48000

I could cut down the number of files in my limits.d directory considerably.

**Comment by saz** [comment]
PR has been merged to master. I'll drop a new release soon.
