### ISSUE TITLE
README.md indicates that this module does not manage /etc/security/limits.conf.  Why doesn't it?

### ISSUE THREAD

**Issue by bschonec** [saz/puppet-limits#43]
Is there a reason this module doesn't manage the limits.conf file?  It would make sense that the module *should* manage the file.  It would be easy enough to add default limits.conf files for RHEL and its variants as well as Debian or other linux-ish distributions.

**Comment by bschonec** [comment]
Any chance you could merge this?

**Comment by bschonec** [comment]
Bump...

**Comment by saz** [comment]
Fixed with the merge of #44
