### ISSUE TITLE
Add an "empty" limits_template

### ISSUE THREAD

**Issue by loood** [saz/puppet-limits#47]
Would like to see a template that has nothing in it except for the "# This file is managed by Puppet.  Do not edit!" messages.

**Comment by saz** [comment]
@loood What's the idea behind it?

**Comment by loood** [comment]
Want to manage `/etc/security/limits.conf` to be basically empty except for that header as all configured limits are actually being written to inside the  `/etc/security/limits.d` directory instead.

**Comment by saz** [comment]
There's now an empty template available `generic_empty.erb`
